/* code/sql/HW_DEFAULT_test.sql */

DROP SCHEMA IF EXISTS HW_DEFAULT_test;
CREATE SCHEMA HW_DEFAULT_test;
USE HW_DEFAULT_test;

CREATE TABLE TEST(
    TestA VARCHAR(15),
    TestB INT,
    TestC FLOAT,
    TestD BOOLEAN,
    TestE BIT(1),
    TestF DATE
);

INSERT INTO TEST VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

SELECT * FROM TEST;
