/* code/sql/HW_FK_test.sql */

DROP SCHEMA IF EXISTS HW_FKtest;

CREATE SCHEMA HW_FKtest;

USE HW_FKtest;

CREATE TABLE TARGET(
    Test VARCHAR(15) PRIMARY KEY
);

CREATE TABLE SOURCE(
    Test VARCHAR(25),
    FOREIGN KEY (Test) REFERENCES TARGET(Test)
);
